### ISSUE TITLE
NKFrameLayoutKit framework

### ISSUE THREAD

**Issue by kennic** [layoutBox/LayoutFrameworkBenchmark#11]
Can you add my [NKFrameLayoutKit](https://github.com/kennic/NKFrameLayoutKit) framework to benchmark results?
I've added my framework to the [benchmark project](https://github.com/kennic/LayoutFrameworkBenchmark)
and here's the [NKFrameLayoutKit benchmark's source code](https://github.com/kennic/LayoutFrameworkBenchmark/blob/master/LayoutFrameworkBenchmark/Benchmarks/NKFrameLayoutKit/NKFrameLayoutKitView.swift)

**Comment by lucdion** [comment]
Hi @kennic, you need to create a Pull Request with all your changes.
